locals = {
  bastion_autoscaling_group_ids     = ["${aws_autoscaling_group.bastions-kubernetesazat-com.id}"]
  bastion_security_group_ids        = ["${aws_security_group.bastion-kubernetesazat-com.id}"]
  bastions_role_arn                 = "${aws_iam_role.bastions-kubernetesazat-com.arn}"
  bastions_role_name                = "${aws_iam_role.bastions-kubernetesazat-com.name}"
  cluster_name                      = "kubernetesazat.com"
  master_autoscaling_group_ids      = ["${aws_autoscaling_group.master-us-west-2a-masters-kubernetesazat-com.id}", "${aws_autoscaling_group.master-us-west-2b-masters-kubernetesazat-com.id}", "${aws_autoscaling_group.master-us-west-2c-masters-kubernetesazat-com.id}"]
  master_security_group_ids         = ["${aws_security_group.masters-kubernetesazat-com.id}"]
  masters_role_arn                  = "${aws_iam_role.masters-kubernetesazat-com.arn}"
  masters_role_name                 = "${aws_iam_role.masters-kubernetesazat-com.name}"
  node_autoscaling_group_ids        = ["${aws_autoscaling_group.nodes-kubernetesazat-com.id}"]
  node_security_group_ids           = ["${aws_security_group.nodes-kubernetesazat-com.id}"]
  node_subnet_ids                   = ["${aws_subnet.us-west-2a-kubernetesazat-com.id}", "${aws_subnet.us-west-2b-kubernetesazat-com.id}", "${aws_subnet.us-west-2c-kubernetesazat-com.id}"]
  nodes_role_arn                    = "${aws_iam_role.nodes-kubernetesazat-com.arn}"
  nodes_role_name                   = "${aws_iam_role.nodes-kubernetesazat-com.name}"
  region                            = "us-west-2"
  route_table_private-us-west-2a_id = "${aws_route_table.private-us-west-2a-kubernetesazat-com.id}"
  route_table_private-us-west-2b_id = "${aws_route_table.private-us-west-2b-kubernetesazat-com.id}"
  route_table_private-us-west-2c_id = "${aws_route_table.private-us-west-2c-kubernetesazat-com.id}"
  route_table_public_id             = "${aws_route_table.kubernetesazat-com.id}"
  subnet_us-west-2a_id              = "${aws_subnet.us-west-2a-kubernetesazat-com.id}"
  subnet_us-west-2b_id              = "${aws_subnet.us-west-2b-kubernetesazat-com.id}"
  subnet_us-west-2c_id              = "${aws_subnet.us-west-2c-kubernetesazat-com.id}"
  subnet_utility-us-west-2a_id      = "${aws_subnet.utility-us-west-2a-kubernetesazat-com.id}"
  subnet_utility-us-west-2b_id      = "${aws_subnet.utility-us-west-2b-kubernetesazat-com.id}"
  subnet_utility-us-west-2c_id      = "${aws_subnet.utility-us-west-2c-kubernetesazat-com.id}"
  vpc_cidr_block                    = "${aws_vpc.kubernetesazat-com.cidr_block}"
  vpc_id                            = "${aws_vpc.kubernetesazat-com.id}"
}
